version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: greenlight
      POSTGRES_USER: greenlight
      POSTGRES_PASSWORD: pa55word
      PGDATA: /data/postgres
    volumes:
      - ./postgres_data:/data/postgres
    ports:
      - "5432:5432"